version: '3.3'

services:
  terransible:
    build: 
      context: .
      args:
        terraform_version: "0.11.13"
    volumes:
        - ${SSH_PRIV_FOLDER}:/root/.ssh:ro
        - ./terraform:/workspace/terraform
    tty: true