---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Enable amazon-linux-extras packages php7 and mariadb
      shell: "amazon-linux-extras enable php7.2 lamp-mariadb10.2-php7.2"
      become: yes
      become_method: sudo
    - name: Install Apache, PHP and MySQL
      yum:
        name:
          - httpd
          - php
          - mariadb-server
          - php-mysqlnd
        state: present
      become: yes
      become_method: sudo
    - name: Download WordPress
      get_url: url=http://wordpress.org/wordpress-latest.tar.gz dest=/var/www/html/wordpress.tar.gz force=yes
    - name: Extract WordPress
      command: "tar xzf /var/www/html/wordpress.tar.gz -C /var/www/html --strip-components 1"
    - name: Make my directory tree readable
      file:
         path: /var/www/html
         mode: u=rwX,g=rX,o=rX
         recurse: yes
         owner: apache
         group: apache
    - name: start mysql (mariadb) server
      become: yes
      command: systemctl start mariadb #debian: mysql
    - name: start mysql (mariadb) on every reboot
      become: yes
      command: systemctl enable mariadb #debian: mysql
    - name: Start apache
      become: yes
      command: systemctl start httpd
    - name: Make sure apache is started at boot
      become: yes
      command: systemctl enable httpd
    
